apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: qwiklabs-gcp-01-45608046e7e8/my-repository/hello-cloudbuild-dev:v1.0
        ports:
        - containerPort: 8080
